basePath: /
definitions:
  domain.Action:
    enum:
    - update
    - delete
    type: string
    x-enum-varnames:
    - Update
    - Delete
  domain.BudgetBillCategory:
    enum:
    - house
    - entertainment
    - personal
    - vehicle_transportation
    - education
    - services
    - financial
    - saving
    - others
    type: string
    x-enum-varnames:
    - House
    - Entertainment
    - Personal
    - Vehicle_Transportation
    - Education
    - Services
    - Financial
    - Saving
    - Others
  domain.BudgetSection:
    enum:
    - main
    - available
    - bill
    type: string
    x-enum-varnames:
    - Main
    - Available
    - Bill
  model.ChangeRequest:
    properties:
      action:
        allOf:
        - $ref: '#/definitions/domain.Action'
        enum:
        - update
        - delete
      detail:
        additionalProperties: {}
        type: object
      id:
        minimum: 1
        type: integer
      section:
        allOf:
        - $ref: '#/definitions/domain.BudgetSection'
        enum:
        - main
        - available
        - bill
    required:
    - action
    - id
    - section
    type: object
  model.ChangeResponse:
    properties:
      change:
        $ref: '#/definitions/model.ChangeRequest'
      error:
        type: string
    type: object
  model.CreateAvailableRequest:
    properties:
      budgetId:
        minimum: 1
        type: integer
      name:
        maxLength: 40
        type: string
    required:
    - budgetId
    - name
    type: object
  model.CreateAvailableResponse:
    properties:
      id:
        type: integer
    type: object
  model.CreateBillRequest:
    properties:
      budgetId:
        minimum: 1
        type: integer
      category:
        allOf:
        - $ref: '#/definitions/domain.BudgetBillCategory'
        enum:
        - house
        - entertainment
        - personal
        - vehicle_transportation
        - education
        - services
        - financial
        - saving
        - others
      description:
        maxLength: 200
        type: string
    required:
    - budgetId
    - category
    - description
    type: object
  model.CreateBillResponse:
    properties:
      id:
        type: integer
    type: object
  model.CreateBillTransactionRequest:
    properties:
      amount:
        type: number
      billId:
        minimum: 1
        type: integer
      description:
        maxLength: 500
        type: string
    required:
    - amount
    - billId
    - description
    type: object
  model.LoginRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  model.LoginResponse:
    properties:
      expiresAt:
        type: integer
      token:
        type: string
    type: object
  model.ReadByIDResponse:
    properties:
      additionalIncome:
        type: number
      availables:
        items:
          $ref: '#/definitions/model.ReadByIDResponseAvailable'
        type: array
      bills:
        items:
          $ref: '#/definitions/model.ReadByIDResponseBill'
        type: array
      fixedIncome:
        type: number
      id:
        type: integer
      month:
        type: integer
      name:
        type: string
      year:
        type: integer
    type: object
  model.ReadByIDResponseAvailable:
    properties:
      amount:
        type: number
      id:
        type: integer
      name:
        type: string
    type: object
  model.ReadByIDResponseBill:
    properties:
      amount:
        type: number
      category:
        $ref: '#/definitions/domain.BudgetBillCategory'
      complete:
        type: boolean
      description:
        type: string
      dueDate:
        type: integer
      id:
        type: integer
      payment:
        type: number
    type: object
  model.ReadLogsResponse:
    properties:
      createdAt:
        type: string
      description:
        type: string
      detail:
        additionalProperties: {}
        type: object
      id:
        type: integer
    type: object
  model.ReadResponse:
    properties:
      id:
        type: integer
      month:
        type: integer
      name:
        type: string
      pendingBills:
        type: integer
      totalAvailable:
        type: number
      totalPending:
        type: number
      totalSaving:
        type: number
      year:
        type: integer
    type: object
  your-accounts-api_budgets_infrastructure_model.CreateRequest:
    properties:
      cloneId:
        minimum: 1
        type: integer
      name:
        maxLength: 40
        type: string
    type: object
  your-accounts-api_budgets_infrastructure_model.CreateResponse:
    properties:
      id:
        type: integer
    type: object
  your-accounts-api_users_infrastructure_model.CreateRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  your-accounts-api_users_infrastructure_model.CreateResponse:
    properties:
      id:
        type: integer
    type: object
info:
  contact:
    email: jonathancastaneda@jsc-developer.me
    name: Your Accounts Support
  description: This is the API from project Your Accounts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Your Accounts API
  version: "1.0"
paths:
  /:
    get:
      description: get the status of server
      produces:
      - text/plain
      responses:
        "200":
          description: Status available
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Show the status of server
      tags:
      - main
  /api/v1/budget/:
    get:
      description: read budgets associated to an user
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: path
        name: user
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ReadResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Read budgets by user
      tags:
      - budget
    post:
      consumes:
      - application/json
      description: create a new budget
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Budget data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/your-accounts-api_budgets_infrastructure_model.CreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/your-accounts-api_budgets_infrastructure_model.CreateResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create budget
      tags:
      - budget
  /api/v1/budget/{id}:
    delete:
      description: Delete an budget by ID
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Budget ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete budget
      tags:
      - budget
    get:
      description: read budget by ID
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Budget ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ReadByIDResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Read budget by ID
      tags:
      - budget
    put:
      consumes:
      - application/json
      description: receive changes associated to a budget
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Budget ID
        in: path
        name: id
        required: true
        type: integer
      - description: Changes data
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/model.ChangeRequest'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/model.ChangeResponse'
            type: array
      summary: Receive changes in budget
      tags:
      - budget
  /api/v1/budget/available/:
    post:
      consumes:
      - application/json
      description: create a new available for budget
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Available data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateAvailableRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.CreateAvailableResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create available for budget
      tags:
      - budget
  /api/v1/budget/bill/:
    post:
      consumes:
      - application/json
      description: create a new bill for budget
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Bill data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateBillRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.CreateBillResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create bill for budget
      tags:
      - budget
  /api/v1/budget/bill/transaction:
    put:
      consumes:
      - application/json
      description: create a new transaction for bill of the budget
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Bill transaction data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateBillTransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create transaction for bill of the budget
      tags:
      - budget
  /api/v1/log/{id}/code/{code}:
    get:
      description: read logs associated to a resource and code
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Resource ID
        in: path
        name: id
        required: true
        type: integer
      - description: Code
        enum:
        - budget
        - budget_bill
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ReadLogsResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Read logs by resource and code
      tags:
      - log
  /login:
    post:
      consumes:
      - application/json
      description: create token for access
      parameters:
      - description: Authentication data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Authenticate user
      tags:
      - user
  /user:
    post:
      consumes:
      - application/json
      description: Create user in the system
      parameters:
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/your-accounts-api_users_infrastructure_model.CreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/your-accounts-api_users_infrastructure_model.CreateResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "409":
          description: Conflict
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create user
      tags:
      - user
swagger: "2.0"
